#!/usr/bin/env bun

import { $ } from "bun";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
process.chdir(ROOT);

await $`git pull`;
await $`bun test --cwd gatekeeper`;
await $`./script/setup`;
await $`./script/dev --browser`;
